### ISSUE TITLE
The dataset files for open-set noise experiments with Places-365 or TingImageNet.

### ISSUE THREAD

**Issue by Openning07** [alibaba/EssentialMC2#5]
Thanks for uploading your source code of NGC.

When I try to reproduce the results in Table.2, where you report the experiments with OOD dataset noise (e.g., from Places-365 or TinyImageNet), and find that you load Places-365 (https://github.com/alibaba/EssentialMC2/blob/main/papers/ICCV2021-NGC/impls/datasets/cifar_noisy_openset_dataset.py#L43) & TinyImageNet (https://github.com/alibaba/EssentialMC2/blob/main/papers/ICCV2021-NGC/impls/datasets/cifar_noisy_openset_dataset.py#L45) from .npy files. But I cannot found any uploaded files for it.

Would you like to upload the missing npy files to make the reproduce complete? Thank you for your valuable attentions and I will be appreciated for any reply.

**Comment by Openning07** [comment]
Hello.

I created one .npy files by resizing all the images from TinyImageNet to 32 x 32 and conducted the experiments. And I failed to reproduce the results in Table.2.

Does anyone manage to reproduce the results? Thanks.

**Comment by Logistic1994** [comment]
We will release the dataset in a week.

**Comment by Logistic1994** [comment]
> Hello.
> 
> I created one .npy files by resizing all the images from TinyImageNet to 32 x 32 and conducted the experiments. And I failed to reproduce the results in Table.2.
> 
> Does anyone manage to reproduce the results? Thanks.

Refer https://github.com/alibaba/EssentialMC2/tree/main/papers/ICCV2021-NGC#datasets.
